function result = EmptyResult(name,caseId,kind)
assert(ismember(kind,{'path','trajectory'}));
result = struct('schema_version','CommonParking-result-1', ...
    'planner',char(name),'case_id',caseId,'kind',kind, ...
    'reference_point','rear_axle_midpoint', ...
    'units',struct('length','m','angle','rad','time','s'), ...
    'status',struct('success',false,'code','not_solved','message',''), ...
    'computation_time_s',NaN,'path',[],'trajectory',[], ...
    'solver',struct(),'diagnostics',struct());
end
