function o=Config()
% Paper values and explicitly chosen finite numerical realization.
o=struct('gridPoints',101,'padding',5,'horizon',8,'speed',1, ...
 'targetXY',.35,'targetHeading',8*pi/180,'cfl',.4, ...
 'forwardResolution',.5,'backwardResolution',.3,'headingResolution',5*pi/180, ...
 'stepFactor',1.5,'steeringSamples',5,'connectedCount',20,'maximumWorkers',12, ...
 'maximumExpanded',15000,'branchSeconds',60,'seedBase',2026128,'outputSpacing',.05);
end
