function options = Config()
% Zhang, Liniger, Sakai & Borrelli, CDC 2018, Eq. (7).
options.nodes=200;options.clearance=.01;
options.controlWeights=[.01 .1];options.rateWeights=[.1 .1];
options.timeWeightPerSecond=10; % Paper leaves kappa numerically unspecified.
options.referenceTimeMultiplier=1.5;options.timeScale=[.8 1.2];
options.maxIterations=2000;options.maxCpuSeconds=30;options.maxRestarts=0;
options.search=struct('xyResolution',.3,'thetaResolution',pi/36,'step',.3, ...
    'steeringSamples',5,'collisionStep',.04,'clearance',.01, ...
    'heuristicWeight',1,'reversePenalty',0,'switchPenalty',10, ...
    'steeringChangePenalty',10,'maxExpanded',100000,'maxSeconds',180, ...
    'analyticEvery',1,'variableStep',false,'nonholonomicHeuristic',false);
end
