function o=Config()
% Numerical choices not fixed by Siedentop et al. (FAS 2015).
o=struct('spacing',.75,'headings',32,'edgeLength',14,'padding',5, ...
 'seconds',180,'collisionSpacing',.05,'outputSpacing',.05, ...
 'smoothingNodes',200,'smoothingSeconds',60,'smoothingIterations',100, ...
 'constraintTolerance',1e-5);
end
