function o=Config()
% Static, rear-axle realization of Roesmann et al., ECC 2021, Sections III-D/F.
o.search=struct('xyResolution',.2,'thetaResolution',pi/36,'step',.5, ...
 'collisionStep',.04,'clearance',.12,'heuristicWeight',1,'switchPenalty',1.5, ...
 'reversePenalty',.05,'maxExpanded',100000,'maxSeconds',180,'analyticEvery',5, ...
 'steeringSamples',3,'variableStep',true,'stepScale',.1,'maximumStep',1);
o.intervals=200;o.clearance=.2;o.speedCost=.01;o.minimumDt=.001;o.previousDt=.1;
o.maxIterations=2000;o.maxCpuSeconds=180;o.feasibilityTolerance=1e-6;o.solverTolerance=1e-8;
end
