function options = Config()
% Method-owned settings. Public RunPlanner has no algorithm-specific arguments.
options.search = struct('xyResolution',0.2,'thetaResolution',pi/36, ...
    'step',0.5,'collisionStep',0.04,'clearance',0.12,'heuristicWeight',1, ...
    'switchPenalty',1.5,'reversePenalty',0.05,'maxExpanded',100000, ...
    'maxSeconds',180,'analyticEvery',5,'steeringSamples',3, ...
    'variableStep',true,'stepScale',0.1,'maximumStep',1.0);
options.cg = struct('coarseSpacing',0.4,'fineSpacing',0.08, ...
    'maxIterations',600,'gradientTolerance',1e-3,'stepTolerance',1e-7, ...
    'maxAnchorPasses',12,'wObstacle',0.15,'obstacleRange',1.1, ...
    'wCurvature',3000,'wCurvatureMin',0,'wSmooth',0.5, ...
    'wVoronoi',0.2,'voronoiRange',4,'alpha',1);
end
