function backend=Geometry(c)
% Per-call exact geometry; no saved paths and no reuse across planner calls.
data=hacg.PrepareGeometry(c);
backend=struct('distance',@hacg.ReedsSheppDistance, ...
    'candidates',@hacg.ReedsSheppCandidates, ...
    'canonical',@(a,b,margin,spacing)hacg.CanonicalConnection(a,b,data,margin,spacing), ...
    'free',@(q,margin)hacg.FootprintFree(q,data,margin), ...
    'obstacleDistance',@(point)hacg.BoundaryDistance(point,data));
end
