function [r,parts]=Residual(z,b,env,o)
[p,dt]=teb.Unpack(z,b);m=teb.Motion(p,dt,o);v=env.vehicle;
radiusViolation=zeros(size(dt));turn=abs(m.angle)>1e-12;
radiusViolation(turn)=max(0,1/v.kappa_max-m.chord(turn)./abs(m.angle(turn)));
distance=teb.Distance(p,env);obstacles=max(0,o.clearance-distance);
parts=struct('time',dt,'nonholonomic',m.nonholonomic,'radius',radiusViolation, ...
 'velocity',max(0,abs(m.v)-v.vmax),'yaw',max(0,abs(m.yaw)-env.yawRateMax), ...
 'acceleration',max(0,abs(m.a)-v.amax),'yawAcceleration',max(0,abs(m.yawAcceleration)-env.yawAccelerationMax), ...
 'obstacles',obstacles);
w=sqrt(o.otherWeight);r=[dt;sqrt(o.nonholonomicWeight)*m.nonholonomic;w*radiusViolation; ...
 w*parts.velocity;w*parts.yaw;w*parts.acceleration;w*parts.yawAcceleration;w*obstacles(:)];
end
